print ("enter 2 names")
name1=input ()
name2=input ()
print ("enter 4 nouns")
noun1=input ()
noun2=input ()
noun3=input()
noun4=input()
print ( name1+ " went to the beach with "+ name2+"." )
print ("First they swam in their "+ noun1)
print ("Then, they saw "+noun2+ "and "+noun3)
print ("Lastly, they built a sandcastle out of" +noun4)